// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounting.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (code, name, type, normal_balance)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, type, normal_balance, balance, created_at, updated_at
`

type CreateAccountParams struct {
	Code          string `json:"code"`
	Name          string `json:"name"`
	Type          string `json:"type"`
	NormalBalance string `json:"normal_balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.NormalBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.NormalBalance,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEntryLine = `-- name: CreateEntryLine :one
INSERT INTO entry_lines (journal_entry_id, account_id, debit, credit)
VALUES ($1, $2, $3, $4)
RETURNING id, journal_entry_id, account_id, debit, credit
`

type CreateEntryLineParams struct {
	JournalEntryID uuid.UUID `json:"journal_entry_id"`
	AccountID      uuid.UUID `json:"account_id"`
	Debit          int64     `json:"debit"`
	Credit         int64     `json:"credit"`
}

func (q *Queries) CreateEntryLine(ctx context.Context, arg CreateEntryLineParams) (EntryLine, error) {
	row := q.db.QueryRow(ctx, createEntryLine,
		arg.JournalEntryID,
		arg.AccountID,
		arg.Debit,
		arg.Credit,
	)
	var i EntryLine
	err := row.Scan(
		&i.ID,
		&i.JournalEntryID,
		&i.AccountID,
		&i.Debit,
		&i.Credit,
	)
	return i, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (date, description)
VALUES ($1, $2)
RETURNING id, date, description, created_at
`

type CreateJournalEntryParams struct {
	Date        pgtype.Timestamptz `json:"date"`
	Description string             `json:"description"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry, arg.Date, arg.Description)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, code, name, type, normal_balance, balance, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.NormalBalance,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, code, name, type, normal_balance, balance, created_at, updated_at FROM accounts WHERE code = $1
`

func (q *Queries) GetAccountByCode(ctx context.Context, code string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, code)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.NormalBalance,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrialBalance = `-- name: GetTrialBalance :many
SELECT code, name, type, normal_balance, balance
FROM accounts
ORDER BY code
`

type GetTrialBalanceRow struct {
	Code          string `json:"code"`
	Name          string `json:"name"`
	Type          string `json:"type"`
	NormalBalance string `json:"normal_balance"`
	Balance       int64  `json:"balance"`
}

func (q *Queries) GetTrialBalance(ctx context.Context) ([]GetTrialBalanceRow, error) {
	rows, err := q.db.Query(ctx, getTrialBalance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrialBalanceRow
	for rows.Next() {
		var i GetTrialBalanceRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Type,
			&i.NormalBalance,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, code, name, type, normal_balance, balance, created_at, updated_at FROM accounts ORDER BY code
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.NormalBalance,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT je.id, je.date, je.description, je.created_at, array_to_json(array_agg(el.*)) as lines
FROM journal_entries je
LEFT JOIN entry_lines el ON je.id = el.journal_entry_id
GROUP BY je.id
ORDER BY je.date DESC
`

type ListJournalEntriesRow struct {
	ID          uuid.UUID          `json:"id"`
	Date        pgtype.Timestamptz `json:"date"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Lines       []byte             `json:"lines"`
}

func (q *Queries) ListJournalEntries(ctx context.Context) ([]ListJournalEntriesRow, error) {
	rows, err := q.db.Query(ctx, listJournalEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalEntriesRow
	for rows.Next() {
		var i ListJournalEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.CreatedAt,
			&i.Lines,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts 
SET balance = balance + $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateAccountBalanceParams struct {
	ID      uuid.UUID `json:"id"`
	Balance int64     `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance)
	return err
}
