// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	NormalBalance string             `json:"normal_balance"`
	Balance       int64              `json:"balance"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type EntryLine struct {
	ID             uuid.UUID `json:"id"`
	JournalEntryID uuid.UUID `json:"journal_entry_id"`
	AccountID      uuid.UUID `json:"account_id"`
	Debit          int64     `json:"debit"`
	Credit         int64     `json:"credit"`
}

type JournalEntry struct {
	ID          uuid.UUID          `json:"id"`
	Date        pgtype.Timestamptz `json:"date"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
