// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntryLine(ctx context.Context, arg CreateEntryLineParams) (EntryLine, error)
	CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error)
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByCode(ctx context.Context, code string) (Account, error)
	GetTrialBalance(ctx context.Context) ([]GetTrialBalanceRow, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListJournalEntries(ctx context.Context) ([]ListJournalEntriesRow, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
}

var _ Querier = (*Queries)(nil)
